eureka:
  client:
    register-with-eureka: false
server:
  port: 8020
spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: assurancePolicy
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/assurancePolicy/**
        - id: assurance
          uri: http://localh ost:8070
          predicates:
            - Path=/api/v1/assurance/**